#!/usr/bin/env python3
"""Parse a VTS Leasing Activity Excel export (or a saved leasing report) into rows.

The export has one sheet per asset plus an "Overview - ..." sheet. The deals sheet is
laid out as repeated blocks:

    stage row    a lone stage name ("Proposals", "Touring", "Dead Deals", ...)
    header row   the column labels ("Tenant", "Broker", "Comments", ...)
    data rows    until the block ends

**Columns are located by their header label, never by position.** Which fields appear
in an export is a per-user setting in VTS ("Deal and proposal details"), so someone who
doesn't tick "Broker" gets a sheet where every later column has shifted left. The labels
themselves are fixed by VTS, so they are the reliable anchor. Reading by position instead
fails silently — it would read a broker name as a comment and produce a plausible-looking
diff, which the push step would then write into a landlord's VTS.

Tenant cells are "Name\nCategory\n"; comment cells are "MM/DD/YY - body". The date prefix
is generated by VTS from the comment's log date, so it is stripped here — comparisons and
pushes should always work on the bare body.

Usage:  python parse_report.py <file.xlsx> [--json]
"""
import json
import re
import pathlib
import sys

import os as _os
import sys as _sys
_sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                  "..", "..", "..", "lib"))
from vts_env import ensure_deps
from vts_errors import die, friendly_open
ensure_deps()          # re-execs under the plugin venv if openpyxl is missing

import openpyxl


def expand(p):
    """Windows shells do not expand ~, so every path arg goes through here."""
    return str(pathlib.Path(p).expanduser())


# Header labels VTS emits, mapped to the field names the rest of the toolkit uses.
# Several spellings per field because export templates and VTS versions differ slightly;
# matching is on a normalized (lowercased, whitespace-collapsed) label.
COLUMN_ALIASES = {
    "tenant": "tenant",
    "tenant name": "tenant",
    "broker": "broker",
    "brokers": "broker",
    "tenant broker": "broker",
    "tenant contact": "contact",
    "contact": "contact",
    "contacts": "contact",
    "inquiry type": "inquiry_type",
    "inquiry": "inquiry_type",
    "type of inquiry": "inquiry_type",
    "size": "size",
    "sf": "size",
    "square feet": "size",
    "area": "size",
    "comments": "comment",
    "comment": "comment",
    "latest comment": "comment",
    "notes": "comment",
}

# Fields the toolkit cannot work without.
REQUIRED = {
    "tenant": "Tenant — the name every deal is matched on",
    "comment": "Comments — the whole point of the round trip",
}

DATE_PREFIX = re.compile(r"^\s*\d{1,2}/\d{1,2}/\d{2,4}\s*-\s*")


def norm(text):
    """Normalize a header label for matching."""
    return re.sub(r"\s+", " ", str(text or "").strip().lower()).rstrip(":")


def strip_prefix(comment):
    """Remove VTS's generated 'MM/DD/YY - ' prefix. Returns (body, prefix_or_None)."""
    if not comment:
        return "", None
    text = str(comment)
    m = DATE_PREFIX.match(text)
    if m:
        return text[m.end():].strip(), m.group(0).strip()
    return text.strip(), None


def deals_sheet(wb):
    """Return the deals worksheet, skipping the Overview tab."""
    for name in wb.sheetnames:
        if not name.lower().startswith("overview"):
            return wb[name]
    return wb[wb.sheetnames[0]]


def cell(ws, row, col):
    v = ws.cell(row=row, column=col).value
    return "" if v is None else str(v).strip()


def row_values(ws, row, max_col):
    return [cell(ws, row, c) for c in range(1, max_col + 1)]


def read_header(ws, row, max_col):
    """Map field name -> column index from a header row. Unknown labels are kept too."""
    mapping, extras = {}, {}
    for c in range(1, max_col + 1):
        label = norm(cell(ws, row, c))
        if not label:
            continue
        field = COLUMN_ALIASES.get(label)
        if field and field not in mapping:
            mapping[field] = c
        elif not field:
            extras[label] = c
    return mapping, extras


def is_header_row(ws, row, max_col):
    """A header row is one that carries the Tenant label."""
    for c in range(1, max_col + 1):
        if norm(cell(ws, row, c)) in ("tenant", "tenant name"):
            return True
    return False


def parse(path):
    wb = friendly_open(path, "report")
    ws = deals_sheet(wb)
    max_col = max(ws.max_column, 8)

    # Title/as-of sit above the first block. Take the first two non-empty cells found,
    # scanning across rather than assuming column C.
    title = as_of = ""
    for r in range(1, min(ws.max_row, 10) + 1):
        if is_header_row(ws, r, max_col):
            break
        for c in range(1, max_col + 1):
            v = cell(ws, r, c)
            if v:
                if not title:
                    title = v
                elif not as_of and v != title:
                    as_of = v
                break

    rows = []
    stage = None
    colmap, extras_map = {}, {}
    seen_any_header = False
    r = 1

    while r <= ws.max_row:
        vals = row_values(ws, r, max_col)
        nonempty = [v for v in vals if v]

        if not nonempty:
            r += 1
            continue

        # Header row: re-read the column layout. Blocks repeat it, and re-reading each
        # time costs nothing while surviving a sheet whose blocks somehow differ.
        if is_header_row(ws, r, max_col):
            colmap, extras_map = read_header(ws, r, max_col)
            seen_any_header = True
            r += 1
            continue

        # A row with exactly one value, immediately followed by a header row, is a
        # section heading. Structural rather than matching a fixed list of stage names,
        # so custom or renamed VTS stages still parse.
        if len(nonempty) == 1 and r + 1 <= ws.max_row and is_header_row(ws, r + 1, max_col):
            stage = nonempty[0]
            r += 1
            continue

        if not colmap:
            r += 1
            continue

        tenant_col = colmap.get("tenant")
        raw_tenant = cell(ws, r, tenant_col) if tenant_col else ""
        if not raw_tenant:
            r += 1
            continue

        # "Name\nCategory\n"
        parts = [p for p in raw_tenant.split("\n") if p.strip()]
        tenant = parts[0].strip() if parts else ""
        category = parts[1].strip() if len(parts) > 1 else ""
        if not tenant:
            r += 1
            continue

        def get(field):
            c = colmap.get(field)
            return cell(ws, r, c) if c else ""

        body, prefix = strip_prefix(get("comment"))

        rows.append({
            "row": r,
            "stage": stage,
            "tenant": tenant,
            "category": category,
            "broker": get("broker"),
            "contact": get("contact"),
            "inquiry_type": get("inquiry_type"),
            "size": get("size"),
            "comment": body,
            "comment_date": prefix,
            "extra": {label: cell(ws, r, c) for label, c in extras_map.items()},
        })
        r += 1

    if not seen_any_header:
        die("This doesn't look like a VTS leasing export.",
            f"File: {pathlib.Path(path).name}",
            ["The sheet has no 'Tenant' column heading, so there's nothing to read.",
             "Make sure this is the Leasing Activity Excel export from VTS, not a "
             "different report or a file that's been heavily reformatted.",
             "If you re-arranged or deleted the heading row while editing, restore it — "
             "the toolkit finds each column by its heading."],
            "no header row containing 'Tenant' found")

    missing = [why for field, why in REQUIRED.items() if field not in colmap]
    if missing:
        die("This export is missing a column the toolkit needs.",
            "Missing: " + "; ".join(missing),
            ["In VTS, open the Export settings, go to 'Deal and proposal details', and "
             "tick the missing field, then export again.",
             "Comments must be set to show at least the last comment."],
            f"header row present but lacked: {sorted(set(REQUIRED) - set(colmap))}")

    return {
        "title": title,
        "as_of": as_of,
        "sheet": ws.title,
        "columns": {f: openpyxl.utils.get_column_letter(c) for f, c in sorted(colmap.items())},
        "missing_columns": sorted(set(COLUMN_ALIASES.values()) - set(colmap)),
        "deals": rows,
    }


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    data = parse(expand(sys.argv[1]))
    if "--json" in sys.argv:
        print(json.dumps(data, indent=2))
        return

    print(f"{data['title']}  |  {data['as_of']}  |  {len(data['deals'])} deals")
    cols = ", ".join(f"{f}={letter}" for f, letter in data["columns"].items())
    print(f"columns found: {cols}")
    if data["missing_columns"]:
        print(f"not in this export: {', '.join(data['missing_columns'])}")

    by_stage = {}
    for d in data["deals"]:
        by_stage.setdefault(d["stage"] or "(no section)", []).append(d)
    for stage, items in by_stage.items():
        print(f"\n{stage} ({len(items)})")
        for d in items:
            print(f"  {d['tenant']:<38} {d['comment'][:70]}")


if __name__ == "__main__":
    main()
