#!/usr/bin/env python3
"""Parse a VTS Leasing Activity Excel export (or a saved leasing report) into rows.

The export has one sheet per asset plus an "Overview - ..." sheet. The deals
sheet is laid out as repeated blocks:

    C<n>   = stage name  ("Proposals", "Touring", "Inquiries", "Idle", "Dead Deals", ...)
    C<n+1> = header row  ("Tenant", "Broker", "Tenant contact", ...)
    C<n+2> = first data row, and so on until a blank/short row

Tenant cells are "Name\nCategory\n"; comment cells are "MM/DD/YY - body".
The date prefix is generated by VTS from the comment's log date, so it is
stripped here — comparisons and pushes should always work on the bare body.

Usage:  python parse_report.py <file.xlsx> [--json]
"""
import json
import re
import pathlib
import sys

import os as _os
import sys as _sys
_sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                                  "..", "..", "..", "lib"))
from vts_env import ensure_deps
from vts_errors import friendly_open
ensure_deps()          # re-execs under the plugin venv if openpyxl is missing

import openpyxl


def expand(p):
    """Windows shells do not expand ~, so every path arg goes through here."""
    return str(pathlib.Path(p).expanduser())


# VTS pipeline stages, in funnel order. "Idle" and "Dead Deals" sit outside the
# funnel but appear as their own sections in the export.
STAGES = [
    "Inquiries", "Touring", "Proposals", "LOI", "Legal",
    "Leases Out", "Leases Executed", "Idle", "Dead Deals",
]

DATE_PREFIX = re.compile(r"^\s*\d{1,2}/\d{1,2}/\d{2,4}\s*-\s*")


def strip_prefix(comment):
    """Remove VTS's generated 'MM/DD/YY - ' prefix. Returns (body, prefix_or_None)."""
    if not comment:
        return "", None
    text = str(comment)
    m = DATE_PREFIX.match(text)
    if m:
        return text[m.end():].strip(), m.group(0).strip()
    return text.strip(), None


def deals_sheet(wb):
    """Return the deals worksheet, skipping the Overview tab."""
    for name in wb.sheetnames:
        if not name.lower().startswith("overview"):
            return wb[name]
    return wb[wb.sheetnames[0]]


def cell(ws, row, col):
    v = ws.cell(row=row, column=col).value
    return "" if v is None else str(v).strip()


def parse(path):
    wb = friendly_open(path, "report")
    ws = deals_sheet(wb)

    title = cell(ws, 1, 3)
    as_of = cell(ws, 2, 3)

    rows = []
    current_stage = None

    for r in range(1, ws.max_row + 1):
        c = cell(ws, r, 3)
        if not c:
            continue

        # A lone stage name in column C opens a new section.
        if c in STAGES and not cell(ws, r, 4):
            current_stage = c
            continue

        # Header row inside a section.
        if c == "Tenant":
            continue

        if current_stage is None:
            continue

        parts = [p for p in c.split("\n") if p.strip()]
        tenant = parts[0].strip() if parts else ""
        category = parts[1].strip() if len(parts) > 1 else ""
        if not tenant:
            continue

        body, prefix = strip_prefix(cell(ws, r, 8))

        rows.append({
            "row": r,
            "stage": current_stage,
            "tenant": tenant,
            "category": category,
            "broker": cell(ws, r, 4),
            "contact": cell(ws, r, 5),
            "inquiry_type": cell(ws, r, 6),
            "size": cell(ws, r, 7),
            "comment": body,
            "comment_date": prefix,
        })

    return {"title": title, "as_of": as_of, "sheet": ws.title, "deals": rows}


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    data = parse(expand(sys.argv[1]))
    if "--json" in sys.argv:
        print(json.dumps(data, indent=2))
    else:
        print(f"{data['title']}  |  {data['as_of']}  |  {len(data['deals'])} deals")
        by_stage = {}
        for d in data["deals"]:
            by_stage.setdefault(d["stage"], []).append(d)
        for stage in STAGES:
            if stage in by_stage:
                print(f"\n{stage} ({len(by_stage[stage])})")
                for d in by_stage[stage]:
                    print(f"  {d['tenant']:<38} {d['comment'][:70]}")


if __name__ == "__main__":
    main()
